### PR TITLE
feat(scan): support external port scanner(nmap) in host machine

### PR DESCRIPTION
**Pull request by MaineK00n**
# What did you implement:
The port scan implemented at https://github.com/future-architect/vuls/pull/1060 was very simple with `net.DialTimeout`. I would like to make nmap available on the vuls host machine for users who want to take advantage of more advanced scanners.

Since there are many options for nmap, we will implement some of the most commonly used scanning techniques and firewall / IDS options. Details are listed below.
```
SCAN TECHNIQUES:
  -sS/sT/sA/sW/sM: TCP SYN/Connect()/ACK/Window/Maimon scans
  -sN/sF/sX: TCP Null, FIN, and Xmas scans
FIREWALL/IDS EVASION AND SPOOFING:
  -g/--source-port <portnum>: Use given port number
```

Also, add the portScan item to config.toml, but at that time, add a function that can explicitly turn off portscan.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

## Vuls built-in Scanner
- config.toml
```toml
[servers.192-168-0-238]
host                = "192.168.0.238"
port               = "22"
user               = "root"
#sshConfigPath		= "/home/username/.ssh/config"
keyPath            = "/home/mainek00n/.ssh/id_rsa"
scanMode           = ["fast-root"]
scanModules        = ["ospkg", "port"]
```
- log at scan
```terminal
[Apr  5 08:39:49]  INFO [localhost] vuls-v0.15.10-build-20210405_083827_c7f36e9
[Apr  5 08:39:49]  INFO [localhost] Start scanning
[Apr  5 08:39:49]  INFO [localhost] config: /home/mainek00n/github/github.com/MaineK00n/vuls/config.toml
[Apr  5 08:39:49]  INFO [localhost] Validating config...
[Apr  5 08:39:49]  INFO [localhost] Detecting Server/Container OS... 
[Apr  5 08:39:49]  INFO [localhost] Detecting OS of servers... 
[Apr  5 08:39:50]  INFO [localhost] (1/1) Detected: 192-168-0-238: ubuntu 20.04
[Apr  5 08:39:50]  INFO [localhost] Detecting OS of containers... 
[Apr  5 08:39:50]  INFO [localhost] Checking Scan Modes... 
[Apr  5 08:39:50]  INFO [localhost] Detecting Platforms... 
[Apr  5 08:39:51]  INFO [localhost] (1/1) 192-168-0-238 is running on other
[Apr  5 08:39:51]  INFO [192-168-0-238] Scanning OS pkg in fast-root mode
[Apr  5 08:39:51]  INFO [192-168-0-238] apt-get update...
[Apr  5 08:40:42]  INFO [192-168-0-238] Scanning listen port...
[Apr  5 08:40:42]  INFO [192-168-0-238] Using Port Scanner: Vuls built-in Scanner


Scan Summary
================
192-168-0-238	ubuntu20.04	2561 installed, 0 updatable
```

- excerpt from TUI
Screenshot from 2021-04-05 08-45-49

## External Scanner(nmap)
- config.toml
```toml
[servers.192-168-0-238]
host                = "192.168.0.238"
port               = "22"
user               = "root"
#sshConfigPath		= "/home/username/.ssh/config"
keyPath            = "/home/mainek00n/.ssh/id_rsa"
scanMode           = ["fast-root"]
scanModules        = ["ospkg", "port"]

[servers.192-168-0-238.portscan]
scannerBinPath = "/usr/bin/nmap"
hasPrivileged = true
scanTechniques = ["sS"]
sourcePort = "443"
```

- log at scan
```terminal
[Apr  5 09:10:24]  INFO [localhost] vuls-v0.15.10-build-20210405_090830_c7f36e9
[Apr  5 09:10:24]  INFO [localhost] Start scanning
[Apr  5 09:10:24]  INFO [localhost] config: /home/mainek00n/github/github.com/MaineK00n/vuls/config.toml
[Apr  5 09:10:24]  INFO [localhost] Validating config...
[Apr  5 09:10:24]  INFO [localhost] Detecting Server/Container OS... 
[Apr  5 09:10:24]  INFO [localhost] Detecting OS of servers... 
[Apr  5 09:10:24]  INFO [localhost] (1/1) Detected: 192-168-0-238: ubuntu 20.04
[Apr  5 09:10:24]  INFO [localhost] Detecting OS of containers... 
[Apr  5 09:10:24]  INFO [localhost] Checking Scan Modes... 
[Apr  5 09:10:24]  INFO [localhost] Detecting Platforms... 
[Apr  5 09:10:25]  INFO [localhost] (1/1) 192-168-0-238 is running on other
[Apr  5 09:10:25]  INFO [192-168-0-238] Scanning OS pkg in fast-root mode
[Apr  5 09:10:25]  INFO [192-168-0-238] apt-get update...
[Apr  5 09:11:23]  INFO [192-168-0-238] Scanning listen port...
[Apr  5 09:11:23]  INFO [192-168-0-238] Using Port Scanner: External Scanner(PATH: /usr/bin/nmap)
[Apr  5 09:11:23]  INFO [192-168-0-238] External Scanner Apply Options: Scan Techniques: sS, HasPrivileged: true, Source Port: 443


Scan Summary
================
192-168-0-238	ubuntu20.04	2561 installed, 0 updatable
```

- excerpt from TUI
Screenshot from 2021-04-05 09-12-48

# Checklist:
You don't have to satisfy all of the following.

- [x] Write tests
- [x] Write documentation
- [x] Check that there aren't other open pull requests for the same issue/feature
- [x] Format your source code by `make fmt`
- [x] Pass the test by `make test`
- [x] Provide verification config / commands
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES  

# Reference
- document update PR: https://github.com/vulsdoc/vuls/pull/144

### CODE REVIEW

**Comment by kotakanbe** [comment]
## 

```
        [servers.localhost.portscan]
        scannerBinPath = "/usr/bin/nmap"
        #hasPrivileged = true
        scanTechniques = ["sS"]
        sourcePort = "443"
```

```
 ✗  ubuntu@dev  ~│g│s│g│f│vuls  ⎇ 1207~  ./vuls scan localhost
[Apr 23 09:54:04]  INFO [localhost] vuls-v0.15.11-build-20210423_092334_3bafd76
[Apr 23 09:54:04]  INFO [localhost] Start scanning
[Apr 23 09:54:04]  INFO [localhost] config: /home/ubuntu/go/src/github.com/future-architect/vuls/config.toml
[Apr 23 09:54:04]  INFO [localhost] Validating config...
[Apr 23 09:54:04] ERROR [localhost] If not privileged, only TCPConnect Scan(-sT) can be used.
```

##

```
        [servers.localhost.portscan]
        scannerBinPath = "/usr/bin/nmap"
        scanTechniques = ["sT"]
        sourcePort = "443"
```

```
 ✗  ubuntu@dev  ~│g│s│g│f│vuls  ⎇ 1207~  ./vuls scan localhost
[Apr 23 09:55:22]  INFO [localhost] vuls-v0.15.11-build-20210423_092334_3bafd76
[Apr 23 09:55:22]  INFO [localhost] Start scanning
[Apr 23 09:55:22]  INFO [localhost] config: /home/ubuntu/go/src/github.com/future-architect/vuls/config.toml
[Apr 23 09:55:22]  INFO [localhost] Validating config...
[Apr 23 09:55:22] ERROR [localhost] SourcePort Option(-g/--source-port) is incompatible with the default TCPConnect Scan(-sT).
```

##

```
        [servers.localhost.portscan]
        scannerBinPath = "/usr/bin/nmap"
        scanTechniques = ["sT"]
```

works fine.
image

**Comment by kotakanbe** [comment]
## fast-root 

```
  [servers.me]
    user = "ubuntu"
    host = "127.0.0.1"
    keyPath = "/home/ubuntu/.ssh/id_rsa"
    scanMode = ["fast-root"]

    [servers.me.portscan]
    scannerBinPath = "/usr/bin/nmap"
    hasPrivileged = true
    scanTechniques = ["sS"]
    sourcePort = "443"
```

```
 ✗  ubuntu@dev  ~│g│s│g│f│vuls  ⎇ 1207~  ./vuls scan me
[Apr 23 10:16:20]  INFO [localhost] vuls-v0.15.11-build-20210423_092334_3bafd76
[Apr 23 10:16:20]  INFO [localhost] Start scanning
[Apr 23 10:16:20]  INFO [localhost] config: /home/ubuntu/go/src/github.com/future-architect/vuls/config.toml
[Apr 23 10:16:20]  INFO [localhost] Validating config...
[Apr 23 10:16:20]  INFO [localhost] Detecting Server/Container OS...
[Apr 23 10:16:20]  INFO [localhost] Detecting OS of servers...
[Apr 23 10:16:20]  INFO [localhost] (1/1) Detected: me: ubuntu 18.04
[Apr 23 10:16:20]  INFO [localhost] Detecting OS of containers...
[Apr 23 10:16:20]  INFO [localhost] Checking Scan Modes...
[Apr 23 10:16:20]  INFO [localhost] Detecting Platforms...
[Apr 23 10:16:21]  INFO [localhost] (1/1) me is running on other
[Apr 23 10:16:21]  INFO [me] Scanning OS pkg in fast-root mode
[Apr 23 10:16:21]  INFO [me] apt-get update...
[Apr 23 10:16:52]  INFO [me] Scanning listen port...
[Apr 23 10:16:52]  INFO [me] Using Port Scanner: External Scanner(PATH: /usr/bin/nmap)
[Apr 23 10:16:52]  INFO [me] External Scanner Apply Options: Scan Techniques: sS, HasPrivileged: true, Source Port: 443
[Apr 23 10:16:52] ERROR [localhost] Error on me, err: [Failed to scan Ports:
    github.com/future-architect/vuls/scanner.Scanner.getScanResults.func1
        /home/ubuntu/go/src/github.com/future-architect/vuls/scanner/serverapi.go:654
  - unable to run nmap scan:
    github.com/future-architect/vuls/scanner.(*base).execExternalPortScan
        /home/ubuntu/go/src/github.com/future-architect/vuls/scanner/base.go:911
  - Couldn't open a raw socket. Error: Operation not permitted (1)]


Scan Summary
================
me      Error           Use configtest subcommand or scan with --debug to view the details


[Apr 23 10:16:52] ERROR [localhost] Failed to scan: Failed to scan. err:
    github.com/future-architect/vuls/scanner.Scanner.Scan
        /home/ubuntu/go/src/github.com/future-architect/vuls/scanner/serverapi.go:103
  - An error occurred on [me]
 ```

```
 ubuntu@dev  ~│g│s│g│f│vuls  ⎇ 1207~  ./vuls configtest me
[Apr 23 10:18:16]  INFO [localhost] vuls-v0.15.11-build-20210423_092334_3bafd76
[Apr 23 10:18:16]  INFO [localhost] Validating config...
[Apr 23 10:18:16]  INFO [localhost] Detecting Server/Container OS...
[Apr 23 10:18:16]  INFO [localhost] Detecting OS of servers...
[Apr 23 10:18:17]  INFO [localhost] (1/1) Detected: me: ubuntu 18.04
[Apr 23 10:18:17]  INFO [localhost] Detecting OS of containers...
[Apr 23 10:18:17]  INFO [localhost] Checking Scan Modes...
[Apr 23 10:18:17]  INFO [localhost] Checking dependencies...
[Apr 23 10:18:17]  INFO [me] Dependencies... Pass
[Apr 23 10:18:17]  INFO [localhost] Checking sudo settings...
[Apr 23 10:18:17]  INFO [me] Checking... sudo checkrestart
[Apr 23 10:18:17]  INFO [me] Checking... sudo stat /proc/1/exe
[Apr 23 10:18:17]  INFO [me] Checking... sudo ls -l /proc/1/exe
[Apr 23 10:18:17]  INFO [me] Checking... sudo cat /proc/1/maps
[Apr 23 10:18:17]  INFO [me] Checking... sudo lsof -i -P
[Apr 23 10:18:18]  INFO [me] Checking... sudo apt-get update
[Apr 23 10:18:22]  INFO [me] Sudo... Pass
[Apr 23 10:18:22]  INFO [localhost] It can be scanned with fast scan mode even if warn or err messages are displayed due to lack of dependent packages or sudo settings in fast-root or deep scan mode
[Apr 23 10:18:22]  INFO [localhost] Scannable servers are below...
me
```

**Review by kotakanbe — CHANGES_REQUESTED** [review]

**Comment by MaineK00n** [comment]
Since nmap uses raw sockets and other options in many cases, strong privileges are required. Therefore, it is important to assign appropriate capabilities when running vuls as a non-root user.

Here is a quote about the Linux capabilities.
```
For the purpose of performing permission checks, traditional UNIX implementations distinguish two categories of processes: privileged processes (whose effective user ID is 0, referred to as superuser or root), and unprivileged processes (whose effective UID is nonzero). Privileged processes bypass all kernel permission checks, while unprivileged processes are subject to full permission checking based on the process's credentials (usually: effective UID, effective GID, and supplementary group list).

Starting with kernel 2.2, Linux divides the privileges traditionally associated with superuser into distinct units, known as capabilities, which can be independently enabled and disabled. Capabilities are a per-thread attribute. 
```
Refs. [capabilities(7) — Linux manual page](https://man7.org/linux/man-pages/man7/capabilities.7.html)

I prepared the validation as follows.(this commit: a4a0110)
`os.Geteuid()` is used to check if the execution is done by a user with root privileges.

## 1. vuls user = root
vuls user has sufficient privileges to not perform a capability check during validation.

## 2. vuls user = non-root
### 2.1 success
```terminal
$ getcap /usr/bin/nmap
/usr/bin/nmap = cap_net_bind_service,cap_net_admin,cap_net_raw+eip

$ ./vuls scan
...
[Apr 27 02:30:24]  INFO [localhost] Validating config...
[Apr 27 02:30:24]  INFO [localhost] Detecting Server/Container OS...
...
```

### 2.2 not enough capability
- 2.2.1 capability is not set at all
```terminal
$ getcap /usr/bin/nmap

$ ./vuls scan
...
[Apr 27 02:31:15]  INFO [localhost] Validating config...
[Apr 27 02:31:15] ERROR [localhost] Failed to parse getcap outputs. please execute this command: `$ getcap /usr/bin/nmap`. If the following string (`/usr/bin/nmap = ... `) is not displayed, you need to set the capability with the following command. `$ setcap cap_net_raw,cap_net_admin,cap_net_bind_service+eip /usr/bin/nmap`
```

- 2.2.2 lack of capability
```terminal
$ getcap /usr/bin/nmap
/usr/bin/nmap = cap_net_admin,cap_net_raw+eip

$ ./vuls scan
...
[Apr 27 02:32:35]  INFO [localhost] Validating config...
[Apr 27 02:32:35] ERROR [localhost] Not enough capability to execute. needs: ['cap_net_bind_service', 'cap_net_admin', 'cap_net_raw'], actual: [cap_net_admin cap_net_raw]. To fix this, run the following command. `$ setcap cap_net_raw,cap_net_admin,cap_net_bind_service+eip /usr/bin/nmap`
```

### 2.3 lack of capability set
```terminal
$ getcap /usr/bin/nmap
/usr/bin/nmap = cap_net_bind_service,cap_net_admin,cap_net_raw+ei

$ ./vuls scan
...
[Apr 27 02:33:54]  INFO [localhost] Validating config...
[Apr 27 02:33:54] ERROR [localhost] Capability(`cap_net_bind_service,cap_net_admin,cap_net_raw`) must belong to the following capability set(need: eip, actual: ei). To fix this, run the following command. `$ setcap cap_net_raw,cap_net_admin,cap_net_bind_service+eip /usr/bin/nmap`
```

**Review by kotakanbe — APPROVED** [review]

**Comment by kotakanbe** [comment]
```ubuntu@dev  ~│g│s│g│f│vuls  ⎇ 1207~  ./vuls scan --debug  localhost 2>&1 | grep Executing`
time="May 26 08:58:18" level=debug msg="Executing... /usr/bin/nmap -sA --privileged -p 53 127.0.0.53"                                                                                                                                                             
time="May 26 08:58:18" level=debug msg="Executing... /usr/bin/nmap -sA --privileged -p 5433,46624,38929 127.0.0.1"                                                                                                                    
time="May 26 08:58:18" level=debug msg="Executing... /usr/bin/nmap -sA --privileged -p 5433 ::1"                                                                                                                                                               
time="May 26 08:58:19" level=debug msg="Executing... /usr/bin/nmap -sA --privileged -p 3128,22,80 133.242.233.218"                                                                                                                                                     
```

**Comment by kotakanbe** [comment]
LGTM :)

**Pull request merged**
