### PR TITLE
chore: remove rand.Seed()

### PR DESCRIPTION
**Pull request by orangekame3**
# What did you implement:

This commit removes rand.Seed() from scanner package.
See more info 👉 https://pkg.go.dev/math/rand#Seed

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:
You don't have to satisfy all of the following.

- [ ] Write tests
- [ ] Write documentation
- [x] Check that there aren't other open pull requests for the same issue/feature
- [x] Format your source code by `make fmt`
- [x] Pass the test by `make test`
- [ ] Provide verification config / commands
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES

# Reference

* https://blog.github.com/2015-01-21-how-to-write-the-perfect-pull-request/

### CODE REVIEW

**Review by MaineK00n — COMMENTED** [review]
Is it necessary to change from math/rand to crypto/rand?

**Comment by orangekame3** [comment]
@MaineK00n 
Thanks for  your feedback.
Starting from Go 1.20, using math/rand's Seed method is deprecated. For improved security and genuine randomness, crypto/rand is recommended. 
In this code, reproducibility isn't a requirement. Therefore, using crypto/rand is a more suitable choice.

**Comment by MaineK00n** [comment]
I'm sure this part is colorizing the log, but is the random number generation performance of crypto/rand necessary for this part?

**Comment by MaineK00n** [comment]
I agree that math/rand.Seed is not necessary.
https://tip.golang.org/doc/go1.20#math/rand

However, I feel that math/rand is sufficient for the random numbers used to determine the color of the log this time.

**Comment by orangekame3** [comment]
@MaineK00n 
I agree that math/rand is sufficient. Therefore, instead of using rand.Seed, how about utilizing NewSource()?

**Comment by orangekame3** [comment]
Sorry, just removing the seeds is sufficient.

**Comment by MaineK00n** [comment]
Since there are only a small number of colors to choose from, I don't think you need to worry too much about seeds or random number generation performance.
https://github.com/future-architect/vuls/blob/d2ca56a515e055b6e8f1d0f5cb3a3be1fb8be56f/config/color.go#L4-L12

**Comment by orangekame3** [comment]
@MaineK00n 
I see. If necessary, I'll remove the Seed() and push the changes. If no modifications are required from the current state, please close the issue.

**Pull request merged**
