### PR TITLE
feat(config) :  Support JSON config

### PR DESCRIPTION
**Pull request by kazuminn**
# What did you implement:
support JSON config.

I actually tested

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Prepare config.json. Please Use https://toml-to-json.matiaskorhonen.fi/
```
$vuls scan;vuls report;vuls tui;
```

# Checklist:
You don't have to satisfy all of the following.

- [ ] Write tests
- [x] Write documentation
- [x] Check that there aren't other open pull requests for the same issue/feature
- [x] Format your source code by `make fmt`
- [x] Pass the test by `make test`
- [x] Provide verification config / commands
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES

### CODE REVIEW

**Comment by kazuminn** [comment]
document https://github.com/vulsdoc/vuls/pull/97

**Comment by kotakanbe** [comment]
Thanks for the sending P/R. 
My honest question is, what would make us happy if vuls supported JSON config. For example, using a jq or something like that to divide and join configuration files flexibly, it would be much cooler.  If anyone has any specific examples, please let me know.

My concern is that there are no test cases around the code, and the number of code to be maintained has increased. As a result the number of issues will be increased.

**Comment by kotakanbe** [comment]
Would anyone be happy if json will be supported?
Thumb up Plz 👍

**Comment by kotakanbe** [comment]
Satisfied enough with TOML format 👍

**Pull request closed without merging**
