### PR TITLE
Sparse dockerization

### PR DESCRIPTION
**Pull request by theonlydoo**
it's not docker hub worthy but with the edition of 3 files you'll have a running vuls in a Docker

### CODE REVIEW

**Comment by kotakanbe** [comment]
Many Thanks :)

Added to README
https://github.com/future-architect/vuls/blob/master/README.md#hello-vuls-in-a-docker-container

**Comment by theonlydoo** [comment]
No problem. You might need to specify that the creation and deployment of
ssh keys is mandatory for this docker to work.

**Comment by kotakanbe** [comment]
Please enhance the readme if you have time :)
https://github.com/future-architect/vuls/blob/master/docker/README.md

**Comment by theonlydoo** [comment]
https://github.com/future-architect/vuls/pull/41

**Pull request merged**
