### PR TITLE
centos add yumopt --disablerepo

### PR DESCRIPTION
**Pull request by yas-ysd**
https://github.com/future-architect/vuls/issues/361

### CODE REVIEW

**Comment by kotakanbe** [comment]
Sorry for may late reply.
I will check after Vuls Festival(3/24) @ TOKYO.

**Comment by kotakanbe** [comment]
In this state, I can not merge your Pull Request.
Please update the code by following procedure and fix the warning.

1. Update to the latest of future-architect/vuls/master
see http://dev.toihrk.me/2015/06/02/github-fork-usage.html

3. `make pretest` and fix warning.
```
$ make pretest
golint cache/bolt.go || exit; golint cache/bolt_test.go || exit; golint cache/db.go || exit; golint commands/cmdutil.go || exit; golint commands/configtest.go || exit; golint commands/discover.go || exit; golint commands/history.go || exit; golint commands/report.go || exit; golint commands/scan.go || exit; golint commands/tui.go || exit; golint commands/util.go || exit; golint config/color.go || exit; golint config/config.go || exit; golint config/jsonloader.go || exit; golint config/loader.go || exit; golint config/tomlloader.go || exit; golint contrib/owasp-dependency-check/parser/parser.go || exit; golint cveapi/cve_client.go || exit; golint main.go || exit; golint models/models.go || exit; golint models/models_test.go || exit; golint report/azureblob.go || exit; golint report/email.go || exit; golint report/email_test.go || exit; golint report/localfile.go || exit; golint report/s3.go || exit; golint report/slack.go || exit; golint report/slack_test.go || exit; golint report/stdout.go || exit; golint report/tui.go || exit; golint report/util.go || exit; golint report/writer.go || exit; golint scan/base.go || exit; golint scan/base_test.go || exit; golint scan/debian.go || exit; golint scan/debian_test.go || exit; golint scan/executil.go || exit; golint scan/freebsd.go || exit; golint scan/freebsd_test.go || exit; golint scan/redhat.go || exit; golint scan/redhat_test.go || exit; golint scan/serverapi.go || exit; golint scan/serverapi_test.go || exit; golint scan/unknownDistro.go || exit; golint util/logutil.go || exit; golint util/util.go || exit; golint util/util_test.go || exit;
scan/redhat.go:309:2: don't use underscores in Go names; var err_repos should be errRepos
scan/redhat.go:310:6: don't use underscores in Go names; var result_repos should be resultRepos
scan/redhat.go:328:7: don't use underscores in Go names; range var err_repo should be errRepo
scan/redhat.go:328:17: should omit 2nd value from range; this loop is equivalent to `for err_repo := range ...`
scan/redhat.go:507:1: error should be the last type when returning multiple items
scan/redhat.go:507:64: don't use underscores in Go names; method parameter err_repos should be errRepos
scan/redhat.go:522:6: don't use underscores in Go names; var result_repos should be resultRepos
scan/redhat.go:603:71: don't use underscores in Go names; method parameter err_repos should be errRepos
scan/redhat.go:624:7: don't use underscores in Go names; range var err_repo should be errRepo
scan/redhat.go:624:17: should omit 2nd value from range; this loop is equivalent to `for err_repo := range ...`
scan/redhat_test.go:1073:2: don't use underscores in Go names; var err_repos should be errRepos
scan/redhat_test.go:1075:23: don't use underscores in Go names; var result_repos should be resultRepos
scan/redhat_test.go:1166:23: don't use underscores in Go names; var result_repos should be resultRepos
#  @-go get -v golang.org/x/tools/cmd/vet
go vet ./.; go vet ./config; go vet ./models; go vet ./report; go vet ./cveapi; go vet ./scan; go vet ./util; go vet ./commands; go vet ./cache;
scan/redhat.go:534: arg err_repos for printf verb %s of wrong type: map[string]bool
exit status 1
gofmt -d cache/bolt.go; gofmt -d cache/bolt_test.go; gofmt -d cache/db.go; gofmt -d commands/cmdutil.go; gofmt -d commands/configtest.go; gofmt -d commands/discover.go; gofmt -d commands/history.go; gofmt -d commands/report.go; gofmt -d commands/scan.go; gofmt -d commands/tui.go; gofmt -d commands/util.go; gofmt -d config/color.go; gofmt -d config/config.go; gofmt -d config/jsonloader.go; gofmt -d config/loader.go; gofmt -d config/tomlloader.go; gofmt -d contrib/owasp-dependency-check/parser/parser.go; gofmt -d cveapi/cve_client.go; gofmt -d main.go; gofmt -d models/models.go; gofmt -d models/models_test.go; gofmt -d report/azureblob.go; gofmt -d report/email.go; gofmt -d report/email_test.go; gofmt -d report/localfile.go; gofmt -d report/s3.go; gofmt -d report/slack.go; gofmt -d report/slack_test.go; gofmt -d report/stdout.go; gofmt -d report/tui.go; gofmt -d report/util.go; gofmt -d report/writer.go; gofmt -d scan/base.go; gofmt -d scan/base_test.go; gofmt -d scan/debian.go; gofmt -d scan/debian_test.go; gofmt -d scan/executil.go; gofmt -d scan/freebsd.go; gofmt -d scan/freebsd_test.go; gofmt -d scan/redhat.go; gofmt -d scan/redhat_test.go; gofmt -d scan/serverapi.go; gofmt -d scan/serverapi_test.go; gofmt -d scan/unknownDistro.go; gofmt -d util/logutil.go; gofmt -d util/util.go; gofmt -d util/util_test.go;
```

**Comment by yas-ysd** [comment]
golint scan/redhat.go
golint scan/redhat_test.go
gofmt -d scan/redhat_test.go
gofmt -d scan/redhat.go
go vet ./scan

successful

**Comment by yas-ysd** [comment]
merge upstream/master

**Pull request closed without merging**
