### PR TITLE
Freebsd jails

### LINKED ISSUE #453: Support for FreeBSD jails
# Environment

## Vuls

Version : vuls 0.3.0.19 

## OS
- Target Server: FreeBSD 11.1-RELEAE
- Vuls Server: FreeBSD 11.1-RELEAE

## Feature request: Support for FreeBSD jails
It would be very nice to have support for jails, and I think it would be fairly easy to implement. Jails can be handeled in very much the same way as a lxc container.

### List jails
```
# jls name
jail1
jail2
jail3
```

### Execute code inside jail with "host user"
```
### jexec -u <user> jail3 hostname -s
jail3
```

### Execute code inside jail with "host user"
```
# jexec -U <user> jail3 hostname -s
jail3
```

### PR DESCRIPTION
**Pull request by ankerstal**
## What did you implement:

sort of closes #453

## How did you implement it:
Started to read up on the code tonight and tried to fiddle with it and get it to work with FreeBSD jails. 

I basically copied the code for lxc and changed it to match how jails work. And in a very simple case with four jails running on a host it seems to work just fine.

```
# ./vuls scan
[Aug  2 00:11:57]  INFO [localhost] Start scanning
[Aug  2 00:11:57]  INFO [localhost] config: /usr/local/etc/vuls/config.toml
[Aug  2 00:11:57]  INFO [localhost] Validating config...
[Aug  2 00:11:57]  INFO [localhost] Detecting Server/Container OS... 
[Aug  2 00:11:57]  INFO [localhost] Detecting OS of servers... 
[Aug  2 00:12:03]  INFO [localhost] (1/1) Detected: core: FreeBSD 11.1-RELEASE
[Aug  2 00:12:03]  INFO [localhost] Detecting OS of containers... 
[Aug  2 00:12:17]  INFO [localhost] Detected: system@core: FreeBSD 11.1-RELEASE
[Aug  2 00:12:17]  INFO [localhost] Detected: ap@core: FreeBSD 11.1-RELEASE
[Aug  2 00:12:17]  INFO [localhost] Detecting Platforms... 
[Aug  2 00:12:19]  INFO [localhost] (1/3) core is running on other
[Aug  2 00:12:19]  INFO [localhost] (2/3) system on core is running on aws
[Aug  2 00:12:19]  INFO [localhost] (3/3) ap on core is running on aws
[Aug  2 00:12:19]  INFO [localhost] Scanning vulnerabilities... 
[Aug  2 00:12:19]  INFO [localhost] Scanning vulnerable OS packages...
```

***Is this ready for review?:*** NO  
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by kotakanbe** [comment]
@ankerstal  Many Thanks!!
I will test it.

**Comment by kotakanbe** [comment]
@ankerstal 

Several warnings are occurring. Please fix these warnings.
You can check with `make pretest`.

```
$ make pretest                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ...
--- /var/folders/l6/ktcmpw_n3zj59ngmvz74hw5r0000gn/T/gofmt120410102     2017-08-02 11:56:30.000000000 +0900
+++ /var/folders/l6/ktcmpw_n3zj59ngmvz74hw5r0000gn/T/gofmt198602461     2017-08-02 11:56:30.000000000 +0900
@@ -90,12 +90,12 @@
                        return containers, err
                }
                return l.parseLxdPs(stdout)
-    case "jail":
-        stdout, err := l.jailPs("jid name")
-        if err != nil {
-            return containers, err
-        }
-        return l.parseJailPs(stdout)
+       case "jail":
+               stdout, err := l.jailPs("jid name")
+               if err != nil {
+                       return containers, err
+               }
+               return l.parseJailPs(stdout)
        default:
                return containers, fmt.Errorf(
                        "Not supported yet: %s", l.ServerInfo.Containers.Type)
@@ -118,11 +118,11 @@
                return l.parseLxdPs(stdout)

        case "jail":
-       stdout, err := l.jailPs("jid name")
+               stdout, err := l.jailPs("jid name")
                if err != nil {
                        return containers, err
                }
-               return l.parseJailPs(stdout)
+               return l.parseJailPs(stdout)

        default:
                return containers, fmt.Errorf(
@@ -222,7 +222,7 @@

 func (l *base) parseJailPs(stdout string) (containers []config.Container, err error) {
        lines := strings.Split(stdout, "\n")
-       for _,line := range lines {
+       for _, line := range lines {

                fields := strings.Fields(line)
                if len(fields) == 0 {
```

**Comment by kotakanbe** [comment]
@ankerstal 

I'd appreciate if you add a test case :)
Test case of Docker and LXD is helpful.
https://github.com/future-architect/vuls/blob/master/scan/base_test.go

**Comment by ankerstal** [comment]
Ah, It seems Im not that used to vim. The checkin to fix identing actually messed it up. Will fix.

**Comment by ankerstal** [comment]
Added a test case. To the best of my ability..

**Comment by Toshinori-Hayashi** [comment]
Thx @ankerstal.

I tried your pull request.

This pull request works. This pull request requires root privileges.
Because "jexec" requires root privileges.
Therefore, this pull request cannot be scanned in a jail unless it is a "root" user.

I suggest that you change the "jexec" to run with sudo in this pull request. 
If you give sudo permission to ScanUser, ScanUser can scan in the jail.


Please forgive my ugly English. :)

**Comment by ankerstal** [comment]
Hi!

 Im not really sure about how to do this? Should I add sudo to:
                        cmd = fmt.Sprintf(`jexec %s /bin/sh -c "%s"`, c.Container.Name, cmd)?
Thanks.
/Peter.

**Comment by Code0x58** [comment]
I don't think `sudo` is installed by default on FreeBSD, so requiring root to access jails seems like an okay start. That said, at a glance it looks like `sudo` may be a higher level option (from `l.exec(command, noSudo)`). I can have a more thorough look later.

This doesn't appear to use `-u $host_user` or `-U $jail_user` which I think was what the feature request tried to say.

I'll have  proper look tonight.

**Comment by ankerstal** [comment]
What happened whit this?

**Comment by Code0x58** [comment]
I dropped the ball. I think I was going to see if `sudo` would be added added on the outside of `decorateCmd`'s output with some different settings. If that was the case then Toshinori-Hayashi wouldn't have (had) an issue.

This PR doesn't match the signature of the PR, but I think that is okay.

To sort the _FIXME_ in `exitedContainers(…)`: I think you'd need to add ` dying` to your `jsl` params so you can filter out living/dying jails. I do not know jail lifecycles so I am not sure it is practical/meaningful to list dying ones. The name (_dying_) makes me think that it may be better to just exclude them from the live listing, and to report an error if somone tries to get to the _FIXME_ branch.

The codebase isn't fresh in my mind (other projects have my attention) so my review isn't as thorough as I'd like, but if the code works for you and @kotakanbe is happy then I have have no objections to add; if people want more from it then they can raise an issue/PR.

**Comment by kotakanbe** [comment]
@ankerstal @Code0x58 

Sorry for late reply. 
If you fix the confilct, I will merge this P/R.

Thanks

**Comment by justyntemme** [comment]
If this still needs re built with newest code base to avoid conflict please let me know and I will happily do that.

**Pull request closed without merging**
