### PR TITLE
Tasks/fix missing affected packages struct

### PR DESCRIPTION
**Pull request by ohsh6o**
If this Pull Request is work in progress, Add a prefix of “[WIP]” in the title.

# What did you implement:

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 

Fixes future-architect/vuls#1003

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

My team and I have been running forked copies of this code to generate reports with the necessary struct attributes added, thereby allowing reports of vulnerability in application dependency manifests (Pipfile, package.json, Gemfile, et cetera) to be viewable in `vuls tui` and `vulsrepo` as first class citizens.

This is a screenshot running this code against [a dummy sample application](https://github.com/flexion/10x-dux-app/).

vuls_1003_fix

Sample outputs can be provided additionally in this PR, as requested.

# Checklist:
You don't have to satisfy all of the following.

- [ ] Write tests
- [ ] Write documentation
- [X] Check that there aren't other open pull requests for the same issue/feature
- [X] Format your source code by `make fmt`
- [X] Pass the test by `make test`
- [X] Provide verification config / commands
- [X] Enable "Allow edits from maintainers" for this PR
- [X] Update the messages below

***Is this ready for review?:*** YES

# Reference

* https://blog.github.com/2015-01-21-how-to-write-the-perfect-pull-request/

### CODE REVIEW

**Comment by ohsh6o** [comment]
I am not sure if you need more tests for this to improve test coverage, @kotakanbe. If so, let me know, and I will author them. Apologies for not surfacing this sooner!

**Comment by ohsh6o** [comment]
Any feedback on this @kotakanbe?

**Comment by kotakanbe** [comment]
@ohsh6o 
This will cause the OS package and the library package to get mixed up, so make sure you fix the vulsrepo side.
I'm afraid you've done a great job of fixing it.

**Comment by ohsh6o** [comment]
> @ohsh6o
> This will cause the OS package and the library package to get mixed up, so make sure you fix the vulsrepo side.
> I'm afraid you've done a great job of fixing it.

Sorry, perhaps I do not understand. At an abstract level are OS vulnerabilities and libraries are not Package and PackageFixStatus objeects, @kotakanbe? I am trying to understand, but I am kind of confused.

**Comment by kotakanbe** [comment]
The model of vuls does not change.
Have the vulsrepo side deal with it.

https://github.com/ishiDACo/vulsrepo

**Pull request closed without merging**
