### PR TITLE
Fix for #205 ubuntu scan fails

### PR DESCRIPTION
**Pull request by william20111**
Fix for #205 

Just runs another regex that matches the older apt versions output. It works, but its not pretty might want to put something more elegant in. 

Cheers
Will

### CODE REVIEW

**Comment by kotakanbe** [comment]
Would you please add a test case?
https://github.com/future-architect/vuls/blob/master/scan/debian_test.go#L204

**Comment by kotakanbe** [comment]
The copy & paste code is not so good ;)
I think it's better to change Regex pattern like below.

```
func (o *debian) parseAptGetUpgrade(stdout string) (upgradableNames []string, err error) {
	startRe := regexp.MustCompile(`The following packages will be upgraded:`)
*	stopRe := regexp.MustCompile(`^(\d+) (to )?upgrade(d)?,.*`)
	startLineFound, stopLineFound := false, false

	lines := strings.Split(stdout, "\n")
	for _, line := range lines {
		if !startLineFound {
			if matche := startRe.MatchString(line); matche {
				startLineFound = true
			}
			continue
		}
		result := stopRe.FindStringSubmatch(line)
*		if 2 < len(result) {
			numUpgradablePacks, err := strconv.Atoi(result[1])
			if err != nil {
				return nil, fmt.Errorf(
					"Failed to scan upgradable packages number. line: %s", line)
			}
			if numUpgradablePacks != len(upgradableNames) {
				return nil, fmt.Errorf(
					"Failed to scan upgradable packages, expected: %s, detected: %d",
					result[1], len(upgradableNames))
			}
			stopLineFound = true
			o.log.Debugf("Found the stop line. line: %s", line)
			break
		}
		upgradableNames = append(upgradableNames, strings.Fields(line)...)
	}
	if !startLineFound {
		// no upgrades
		return
	}
	if !stopLineFound {
		// There are upgrades, but not found the stop line.
		return nil, fmt.Errorf("Failed to scan upgradable packages")
	}
	return
}
```

**Comment by william20111** [comment]
Yes looks much better! Will change the PR and test

Cheers
Will

**Comment by kotakanbe** [comment]
If you are still using the old version of apt please reopen.

**Pull request closed without merging**
