### PR TITLE
Add Oracle Linux support

### LINKED ISSUE #385: Add support for Oracle Linux
Oracle Linux provides similar security information via `yum` as Red Hat Enterprise Linux and Amazon. However, it has unique advisory IDs and URLs. It should be supported as a standalone distro for recognition and reporting purposes.

### PR DESCRIPTION
**Pull request by Djelibeybi**
Signed-off-by: Avi Miller <avi.miller@oracle.com>

## What did you implement:

Closes #385

## How did you implement it:

Modified the existing `scan/redhat.go` and `scan/redhat_test.go` source to identify Oracle Linux. Also updated `report/util.go` and `report/writer.go` to reference the correct URL for the Oracle Linux CVE and Errata information.

## How can we verify it:

Scan an Oracle Linux Docker image. You can scan `oraclelinux:5`, `oraclelinux:6` and `oraclelinux:7`. The last image/tag is also `oraclelinux:latest`

## Todos:
You don't have to satisfy all of the following.

- [X] Write tests
- [X] Write documentation
- [X] Check that there aren't other open pull requests for the same issue/feature
- [X] Format your source code by `make fmt`
- [X] Pass the test by `make test`
- [X] Provide verification config / commands
- [X] Enable "Allow edits from maintainers" for this PR
- [X] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by kotakanbe** [comment]
@Djelibeybi 

Many thanks. 
LGTM :)  Perfect.

I will merge this P/R.
Would you merge in only one commit?
http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by Djelibeybi** [comment]
@kotakanbe I can squash them, or you can use GitHub's "Squash and Merge" button, which does it automatically for both of us. :)

**Comment by kotakanbe** [comment]
To be honest, I knew it for the first time :)
Thanks!

**Comment by Djelibeybi** [comment]
Yeah, I get lazy these days because I know GitHub can squash things on merge. :)

**Pull request merged**
