### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by lapthorn**
Includes commits from @galigalikun

### CODE REVIEW

**Comment by kotakanbe** [comment]
Thanks for sending P/R.
Sorry for late reply.

I will merge this P/R. 
Would you merge in only one commit?
http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by kotakanbe** [comment]
Many Thanks!

**Comment by lapthorn** [comment]
@kotakanbe rebased into one commit.  Cheers!

**Comment by lapthorn** [comment]
@kotakanbe I thought that was quick - then I realised you were in Japan! ;-)

**Pull request merged**
