### PR TITLE
Missing the else on the assumeYes check.

### PR DESCRIPTION
**Pull request by jsulinski**
#320 
Relates to #266 and #260

### CODE REVIEW

**Comment by kotakanbe** [comment]
else block is not needed.

**Comment by jsulinski** [comment]
I must be missing something. If assumeYes is true, I see no way for it to get to the block for adding servers (below it). 

I don't think the assumeYes feature will work under any circumstances now, so this should be pretty simple to validate. Adding the else condition fixed the issue for me.

**Comment by kotakanbe** [comment]
https://github.com/future-architect/vuls/pull/321/files#diff-0aeee5aa777c1b0180d7273bb84f9199R440

`Yes:` is just a label, so I think that the block under `yes:` will be executed even if assumeYes is true or false.

**Comment by jsulinski** [comment]
ah yeah, thanks.

**Pull request closed without merging**
