### PR TITLE
Stride support

### PR DESCRIPTION
**Pull request by kazuminn**
## What did you implement:

Closes #XXXXX

## Todos:
You don't have to satisfy all of the following.

- [ ] Write tests
- [x] Write documentation
- [x] Check that there aren't other open pull requests for the same issue/feature
- [x] Format your source code by `make fmt`
- [x] Pass the test by `make test`
- [x] Provide verification config / commands
- [x] Enable "Allow edits from maintainers" for this PR
- [ ] Update the messages below

***Is this ready for review?:*** NO  
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by kazuminn** [comment]
https://github.com/vulsdoc/vuls/pull/23
https://github.com/vulsdoc/vuls/pull/24

**Comment by kotakanbe** [comment]
@kazuminn 

Please do `make fmt` before submitting P/R

**Comment by kotakanbe** [comment]
@kazuminn 

StrideConf.Vlaidate have to be called in ValidateOnReport()

```
~/g/s/g/f/vuls on({624}) is(dirty) can(pull) ➜  git diff                                                                                                                                                       721ms
diff --git i/config/config.go w/config/config.go
index c04f481..74842cb 100644
--- i/config/config.go
+++ w/config/config.go
@@ -279,6 +279,9 @@ func (c Config) ValidateOnReport() bool {
                errs = append(errs, hipchaterrs...)
        }

+       if strideerrs := c.Stride.Validate(); 0 < len(strideerrs) {
+               errs = append(errs, strideerrs...)
+       }
        if syslogerrs := c.Syslog.Validate(); 0 < len(syslogerrs) {
                errs = append(errs, syslogerrs...)
        }
@@ -426,13 +429,16 @@ type StrideConf struct {

 // Validate validates configuration
 func (c *StrideConf) Validate() (errs []error) {
+       if !Conf.ToStride {
+               return
+       }

        if len(c.HookURL) == 0 {
-               errs = append(errs, fmt.Errorf("HookURL must not be empty"))
+               errs = append(errs, fmt.Errorf("stride.HookURL must not be empty"))
        }

        if len(c.AuthToken) == 0 {
-               errs = append(errs, fmt.Errorf("AuthToken must not be empty"))
+               errs = append(errs, fmt.Errorf("stride.AuthToken must not be empty"))
        }

        _, err := valid.ValidateStruct(c)
diff --git i/report/stride_test.go w/report/stride_test.go
index 7737ce4..80c499f 100644
--- i/report/stride_test.go
+++ w/report/stride_test.go
@@ -1 +1 @@
-package report
\ No newline at end of file
+package report
```

**Comment by kotakanbe** [comment]
Many thanks!

**Pull request merged**
