### PR TITLE
Fix gocui.NewGui after signature change #261

### PR DESCRIPTION
**Pull request by Code0x58**

### CODE REVIEW

**Comment by kotakanbe** [comment]
Thanks.

Vuls uses glide for package management.
https://github.com/Masterminds/glide

Could you please also update glide.lock?
https://github.com/future-architect/vuls/blob/master/glide.lock

How to update glide.lock
```
delete vendor and glide.lock
glide install
```

Then git commit --amend or merge in only one commit.

**Comment by Code0x58** [comment]
Ah, I thought I must have been missing something profound about Go package
management!

Thanks for the pointer, I'll amend this tonight for the two pull requests.

On 14 Nov 2016 02:55, "Kota Kanbe" <notifications@github.com> wrote:

Thanks.

Vuls uses glide for package management.
https://github.com/Masterminds/glide

Could you please also update glide.lock?
https://github.com/future-architect/vuls/blob/master/glide.lock

How to update glide.lock

delete vendor and glide.lock
glide install

Then git commit --amend or merge in only one commit.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/future-architect/vuls/pull/262#issuecomment-260237570>,
or mute the thread

**Comment by Code0x58** [comment]
I updated all of the dependencies after pinning to the context branch of subcommands (#243).

**Comment by kotakanbe** [comment]
Many Thanks 👍

**Pull request merged**
