### PR TITLE
Changed things from all doing 'sshExec' or 'ssh' to instead do 'exec'…

### PR DESCRIPTION
**Pull request by NickNeedsAName**
….  The goal is to have it so that if you've configured the server to be local (by denoting the host as localhost (or 127.0.0.1) and the port as '' or 'local') you don't go over ssh

### CODE REVIEW

**Comment by NickNeedsAName** [comment]
I have also added a bit of documentation to some of the more opaque code

**Comment by Veraticus** [comment]
Is there a reason this was closed? It seems like it'd be pretty helpful.

**Comment by kotakanbe** [comment]
@NickNeedsAName
If you have a time and still motivated,  would you please send a P/R ?
If not, I will implement the function instead of you :)

**Comment by NickNeedsAName** [comment]
Heyo,

Yea I've got this done.  It's a bit mixed up with a bunch of other changes, I will clean things up for a P/R soon. 

-nick

**Pull request closed without merging**
